# Generated by Django 4.2.18 on 2025-02-10 20:41

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ("versions", "0018_version_financial_committee_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="release_report_cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(
                    bucket_name="stage.boost.org.v2"
                ),
                upload_to="release_report_cover/",
            ),
        ),
    ]
